version: '3.7'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      - container-link
    environment:
      - "VIRTUAL_HOST=${VIRTUAL_HOST}"

    # depends_on:
    #   - db

  # db:
  #   image: postgres
  #   environment:
  #     - "POSTGRES_USER=${POSTGRES_USER}"
  #     - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
