version: '3.7'

# for jwilder/nginx-proxy
networks:
  default:
    external:
      name: bridge
  container-link:
    name: container_network

services:
  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      - container-link
    environment:
      - "VIRTUAL_HOST=${VIRTUAL_HOST}"
      - "LETSENCRYPT_HOST=${VIRTUAL_HOST}"
      - "CERT_NAME=${VIRTUAL_HOST}"

    # depends_on:
    #   - db

  # db:
  #   image: postgres
  #   environment:
  #     - "POSTGRES_USER=${POSTGRES_USER}"
  #     - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
